import { LaneId, ShiftType } from '@/lib/types';
import { mapLane, mapPeriod, normalizeName, shiftLabel } from './map';

/** A normalized assignment ready to upsert into the `roster` table. */
export interface ParsedRosterRow {
  shift_date: string;        // YYYY-MM-DD from a Date column, or '' (import fills from the date picker)
  name: string;
  phone: string;
  shift_type: ShiftType;
  start_time: string;
  end_time: string;
  shift_label: string;
  role: string;
  lane: LaneId;
  source_location: string;
}

export interface RosterParseResult {
  rows: ParsedRosterRow[];
  warnings: string[];
  detectedDate: string | null; // YYYY-MM-DD
}

// ─────────────────────────────────────────────────────────────
// CSV → cell matrix (RFC-4180: quoted fields, "" escapes, embedded
// commas/newlines, CRLF, leading BOM).
// ─────────────────────────────────────────────────────────────
export function parseCsv(text: string): string[][] {
  const src = text.replace(/^﻿/, ''); // strip BOM
  const rows: string[][] = [];
  let row: string[] = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < src.length; i++) {
    const ch = src[i];

    if (inQuotes) {
      if (ch === '"') {
        if (src[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else {
        field += ch;
      }
      continue;
    }

    if (ch === '"') { inQuotes = true; }
    else if (ch === ',') { row.push(field); field = ''; }
    else if (ch === '\r') { /* ignore, handled by \n */ }
    else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else { field += ch; }
  }
  // flush trailing field/row
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

// ─────────────────────────────────────────────────────────────
// Header column resolution
// ─────────────────────────────────────────────────────────────
const COLUMN_SYNONYMS: Record<string, string[]> = {
  date: ['date', 'shift date', 'day date'],
  start: ['start', 'start time', 'from'],
  end: ['end', 'end time', 'to'],
  period: ['period', 'shift', 'shift period'],
  name: ['volunteer', 'name', 'volunteer name', 'full name'],
  role: ['role', 'position', 'assignment'],
  note: ['note', 'notes', 'comment', 'comments'],
  location: ['location', 'area', 'venue', 'site', 'group', 'zone', 'team'],
  phone: ['phone', 'mobile', 'cell', 'contact', 'phone number'],
};

const NAME_HEADER_VALUES = new Set(COLUMN_SYNONYMS.name);

type ColumnMap = Partial<Record<keyof typeof COLUMN_SYNONYMS, number>>;

function resolveHeader(cells: string[]): ColumnMap | null {
  const norm = cells.map((c) => c.trim().toLowerCase());
  const map: ColumnMap = {};
  for (const key of Object.keys(COLUMN_SYNONYMS) as (keyof typeof COLUMN_SYNONYMS)[]) {
    const idx = norm.findIndex((c) => COLUMN_SYNONYMS[key].includes(c));
    if (idx !== -1) map[key] = idx;
  }
  // A valid header must name the person and at least one shift descriptor.
  if (map.name === undefined) return null;
  if (map.period === undefined && map.start === undefined) return null;
  return map;
}

// Lone-cell rows that are titles / totals / footers, not locations.
const NON_LOCATION_ROW =
  /(\d+\s+assignments?|generated by|dispatch roster|national bank open)/i;

// ─────────────────────────────────────────────────────────────
// Date detection ("Friday, July 31, 2026" / "July 31, 2026")
// ─────────────────────────────────────────────────────────────
const MONTHS: Record<string, number> = {
  january: 1, february: 2, march: 3, april: 4, may: 5, june: 6,
  july: 7, august: 8, september: 9, october: 10, november: 11, december: 12,
};

export function detectDateFromText(text: string): string | null {
  // Global scan: skip non-month matches (e.g. "Suite 12, 2026") and return the
  // first "<Month> <day>, <year>" — also accepts ISO "2026-07-31".
  const iso = text.match(/\b(\d{4})-(\d{2})-(\d{2})\b/);
  if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}`;
  const re = /([A-Za-z]+)\s+(\d{1,2}),?\s*(\d{4})/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const month = MONTHS[m[1].toLowerCase()];
    if (!month) continue;
    const day = parseInt(m[2], 10);
    const year = parseInt(m[3], 10);
    if (!day || day > 31) continue;
    return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  }
  return null;
}

export function detectDateFromMatrix(matrix: string[][]): string | null {
  for (const row of matrix) {
    const hit = detectDateFromText(row.join(' '));
    if (hit) return hit;
  }
  return null;
}

// ─────────────────────────────────────────────────────────────
// Core interpreter — shared by CSV and XLSX paths.
// Handles both layouts: a Location column, or location section-header rows
// (as in the PDF export) tracked top-to-bottom.
// ─────────────────────────────────────────────────────────────
export function interpretMatrix(matrix: string[][]): { rows: ParsedRosterRow[]; warnings: string[] } {
  const warnings: string[] = [];
  const rows: ParsedRosterRow[] = [];

  let header: ColumnMap | null = null;
  let currentLocation = '';
  const seen = new Set<string>(); // dedupe identical assignments (would break the upsert)

  // A row holding a single non-empty cell — a location section header in the
  // PDF-style export (e.g. "Tennis Centre"), as opposed to a title/total line.
  const loneLabel = (cells: string[]): string => {
    const nonEmpty = cells.map((c) => c.trim()).filter(Boolean);
    return nonEmpty.length === 1 ? nonEmpty[0] : '';
  };

  for (let i = 0; i < matrix.length; i++) {
    const cells = matrix[i];
    const lineNo = i + 1;
    const joined = cells.join('').trim();
    if (!joined) continue; // blank row

    // First valid header row sets the column map. The very first location section
    // can appear BEFORE that header, so track lone-cell locations here too.
    if (!header) {
      const resolved = resolveHeader(cells);
      if (resolved) { header = resolved; continue; }
      const label = loneLabel(cells);
      if (label && !NON_LOCATION_ROW.test(label)) currentLocation = label;
      continue;
    }

    const get = (key: keyof typeof COLUMN_SYNONYMS): string => {
      const idx = header![key];
      return idx === undefined ? '' : (cells[idx] ?? '').trim();
    };

    const name = normalizeName(get('name'));

    // Repeated header row (ShiftCrew prints it per page) → skip.
    if (NAME_HEADER_VALUES.has(name.toLowerCase())) continue;

    // No name → either a location section header or a title/footer line.
    if (!name) {
      if (header.location === undefined) {
        const label = loneLabel(cells);
        if (label && !NON_LOCATION_ROW.test(label)) currentLocation = label;
      }
      continue;
    }

    const periodRaw = get('period');
    const shift_type = mapPeriod(periodRaw);
    if (!shift_type) {
      warnings.push(`Row ${lineNo}: "${name}" — unrecognized period "${periodRaw || '(blank)'}", skipped.`);
      continue;
    }

    const role = get('role');
    const source_location = header.location !== undefined ? get('location') : currentLocation;
    const lane = mapLane(source_location, role);
    if (!lane) {
      warnings.push(
        `Row ${lineNo}: "${name}" — location "${source_location || '(none)'}" not recognized, placed in Other.`
      );
    }

    const start_time = get('start');
    const end_time = get('end');
    const phone = get('phone');

    // Per-row date from a Date column, if the export has one ("All Days" sheet).
    let shift_date = '';
    const dateRaw = get('date');
    if (dateRaw) {
      const parsed = detectDateFromText(dateRaw);
      if (parsed) shift_date = parsed;
      else warnings.push(`Row ${lineNo}: "${name}" — unrecognized date "${dateRaw}", will use the selected date.`);
    }

    // Dedup key MUST match the DB upsert conflict key (shift_date,name,shift_type,
    // source_location) — otherwise two colliding rows abort the whole upsert.
    const dedupKey = `${shift_date}|${name.toLowerCase()}|${shift_type}|${source_location.toLowerCase()}`;
    if (seen.has(dedupKey)) {
      warnings.push(`Row ${lineNo}: duplicate ${shift_type} assignment for "${name}" at "${source_location || '(none)'}", skipped.`);
      continue;
    }
    seen.add(dedupKey);

    rows.push({
      shift_date,
      name,
      phone,
      shift_type,
      start_time,
      end_time,
      shift_label: shiftLabel(start_time, end_time),
      role,
      lane: lane ?? 'other',
      source_location,
    });
  }

  if (!header) warnings.push('Could not find a header row (expected columns like Period, Volunteer, Start/End).');
  if (header && rows.length === 0) warnings.push('No assignments were found below the header.');

  return { rows, warnings };
}

/** Parse a ShiftCrew CSV export. */
export function parseRosterCsv(text: string): RosterParseResult {
  const matrix = parseCsv(text);
  const { rows, warnings } = interpretMatrix(matrix);
  return { rows, warnings, detectedDate: detectDateFromText(text) ?? detectDateFromMatrix(matrix) };
}

/** Parse a pre-built cell matrix (used by the XLSX path). */
export function parseRosterMatrix(matrix: string[][]): RosterParseResult {
  const { rows, warnings } = interpretMatrix(matrix);
  return { rows, warnings, detectedDate: detectDateFromMatrix(matrix) };
}
